sudo: required
services: 
  - docker

before_install :
  - docker build -t abhijeetbhatt17/docker-react -f Dockerfile.dev .

script :
  - docker run abhijeetbhatt17/docker-react npm run test -- --coverage